---
root: true
plugins:
  - react-refresh
env:
  browser: true
  es2020: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react-hooks/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  react-refresh/only-export-components: 'warn'
